---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glance
resources:
  - ../../base
  - ./external_secrets.yaml
  - ./nodeport.yaml

configMapGenerator:
  - files:
    - glance.yml=configs/glance.yml
    name: glance-config
  - files:
    - favicon.ico=assets/favicon.ico
    name: glance-assets